### ISSUE TITLE
One strange effect when resizing window

### ISSUE THREAD

**Issue by jkleiser** [mciucu/stemjs-demo#3]
When I resize the browser window, the vertical gray border line to the right of the column containing the text "This is a text on the left" keeps moving to the left, making that column more and more narrow. The only way, as far as I know, to restore the original width of that column, is to reload the page.
This happens both in Chrome (56.0.2924.87), Safari (10.0.3) and Firefox (51.0.1).

**Comment by mciucu** [comment]
Thanks for this report, it should be fixed in the latest version of Stem. You can just run `npm update` to get it.
If you don't mind me asking, how did you stumble on this project?

**Comment by jkleiser** [comment]
I did the `npm updat` on my project and that reported "stem-core@0.2.59". Then I cd'ed into src and did `rollup -c`. In Safari I have done "Empty Caches" and activated "Disable Caches" and reloaded the index.html. The strange effect remains. I have tried to clear the caches in Chrome and Firefox also, but I'm not 100% sure I've succeeded. At least the effect remains there too.
I thought it was on Hacker News yesterday, but I cannot confirm it. Is there a connection between Stem.js and https://csacademy.com ?

**Comment by mciucu** [comment]
Sorry about that, there seemed to be another issue from some legacy code, and it's been also patched in Stem. You can try again now.
Stem.js is the javascript framework I developed for csacademy.com internally. It was meant as a basis for interactive and maintainable UI widgets, like the code editor and the lesson players for instance. Over time it grew into a nice collection of components that work well together and exceeded the area of just doing UI, and I recently started efforts to open source it.

**Comment by jkleiser** [comment]
Looks fine now. Thanks.
